# ============================================================
# Caso 2 - Automation Test Store Configuration
# ============================================================

url=http://www.automationteststore.com

browser=chrome

implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Registro
reg.firstname=John
reg.lastname=QA
reg.email=johnqa_envioclick@mailtest.com
reg.address=Calle Reforma 100
reg.city=Ciudad de Mexico
reg.postcode=06600
reg.loginname=johnqa_envioclick
reg.password=Test1234!

# Login
valid.user=johnqa_envioclick
valid.pass=Test1234!
invalid.user=usuariofalso999
invalid.pass=wrongpass

# Divisas
currency.usd=USD
currency.eur=EUR
currency.gbp=GBP

report.path=reports/caso2-automationstore-report.html
report.title=Caso 2 - Automation Test Store QA Report
